version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: plants-store-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: plants_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: plant_nursery_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata: